project_id = "tggurgtvpplkyomsdbwt"

[functions.send-status-email]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.auto-payment-reminder]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.send-follow-up-emails]
verify_jwt = false

[functions.totp-manage]
verify_jwt = false

[functions.publish-scheduled-posts]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.track-newsletter]
verify_jwt = false

[functions.send-scheduled-newsletters]
verify_jwt = false

[functions.unsubscribe-newsletter]
verify_jwt = false

[functions.newsletter-preferences]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.customer-chat]
verify_jwt = false

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false
