project_id = "tggurgtvpplkyomsdbwt"

[functions.send-status-email]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.auto-payment-reminder]
verify_jwt = false

[functions.verify-captcha]
verify_jwt = false
